import "./globals.css";
import Header from "./Header";
import Container from "./Container";

export const metadata = {
  title: "TimeLuxe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
