import "./globals.css";
import Header from "./Header";
import Container from "./Container";
import Footer from "./Footer";


export const metadata = {
  title: "TimeLuxe",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
